### ISSUE TITLE
Unexpected response code: 200

### ISSUE THREAD

**Issue by kalo295** [pbielicki/soapui-websocket-transport#1]
I'm new to Websocket. I've installed soapui-websocket-transport. 
I'm trying a tutorial to connect to soapui websocket (I have SOAPUI 4.5.2 and 5.0.0), but i get this error: "WebSocket connection to 'ws://127.0.0.1:8080/mockWSPortBinding' failed: Error during WebSocket handshake: Unexpected response code: 200". I've read about this error, that means the response status 200 instead of 101.
Can you clarify how did you test with SOAPUI?

**Comment by pbielicki** [comment]
Try using plain Java or JavaScript client to connect to your WS endpoint e.g.
- https://github.com/pbielicki/soap-websocket-cxf/tree/master/soap-websocket-client
- http://www.websocket.org/echo.html

and see if you have the same results

Which server and version are you using? I assume that you have real websocket stuff behind ws://127.0.0.1:8080/mockWSPortBinding ?

**Comment by kalo295** [comment]
Thanks for response. 
I've created a SoapUI mock to test. Do I have to do something to transform the defaut SoapUI webservice to websocket after installing SoapUI Websocket Transport?

**Comment by pbielicki** [comment]
I'm not sure it makes sense what you're doing. SoapUI does not support websocket transport by default. My small add-on makes it possible to send messages to real WS endpoints. I never tested it with mocks. Anyway, transport protocol is not really important for mocks as you want to test the functionality, instead of connectivity layer.

My suggestion: develop a simple websocket server endpoint using any Servlet 3.1 container (e.g. Wildfly 8.0 or Tomcat 8.0): http://docs.oracle.com/javaee/7/tutorial/doc/websocket.htm

You can take my stuff as a starting point https://github.com/pbielicki/soap-websocket-cxf/tree/master/soap-websocket-webapp

**Comment by stephaneeybert** [comment]
Apart from testing and trying over on another starting point, what about the meaning of this 200 as a response ? I'm faced with the same issue http://stackoverflow.com/questions/26891029/websocket-handshake-fails-on-200-from-a-spring-stomp-websocket

**Comment by pbielicki** [comment]
It looks like your endpoint is not a web socket endpoint, that's why you get HTTP 200 (OK) response instead of HTTP 101. Check https://www.websocket.org/aboutwebsocket.html (_"If the server understands the WebSocket protocol, it agrees to the protocol switch through the Upgrade header."_)

**Comment by stephaneeybert** [comment]
It was my being a newbie in Spring websockets and Stomp ignoring how to instantiate it.
The call:
this.stompClient = Stomp.client(ENV.NITRO_PROJECT_WS_URL + '/socket/'
was the issue as it was asking for a ws:// url.
I changed it for the call:
var socket = new SockJS(ENV.NITRO_PROJECT_REST_URL + '/socket/' + endpoint);
this.stompClient = Stomp.over(socket);
to an http:// url and all is fine now.

**Comment by JackyTrad** [comment]
I tried to add WebSocket Transport Plugin for soapUI following: https://github.com/pbielicki/soapui-websocket-transport

Tried to use the demo: ws://echo.websocket.org, by entering it as a wsdl. But I got the error: Wed Dec 17 09:51:14 IST 2014:ERROR:Failed to load url [file:/C:/Program%20Files%20(x86)/SmartBear/soapUI-Pro-4.5.1/bin/ws:/echo.websocket.org]

How I need to send the soap message ? It's look like the soapui is trying to find the wsdl in the local computer...
